# Generated by Django 6.0 on 2025-12-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
