# Generated by Django 6.0 on 2025-12-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_guestuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
